//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaiorumSeries.GedComLogic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MaiorumSeries.GedComLogic.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  and dies on .
        /// </summary>
        public static string AndDiedOn {
            get {
                return ResourceManager.GetString("AndDiedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baptized .
        /// </summary>
        public static string Baptized {
            get {
                return ResourceManager.GetString("Baptized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Born .
        /// </summary>
        public static string Born {
            get {
                return ResourceManager.GetString("Born", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buried .
        /// </summary>
        public static string Buried {
            get {
                return ResourceManager.GetString("Buried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Died .
        /// </summary>
        public static string Died {
            get {
                return ResourceManager.GetString("Died", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  died on .
        /// </summary>
        public static string DiedOn {
            get {
                return ResourceManager.GetString("DiedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  in .
        /// </summary>
        public static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is by profession .
        /// </summary>
        public static string IsByProfession {
            get {
                return ResourceManager.GetString("IsByProfession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Married .
        /// </summary>
        public static string Married {
            get {
                return ResourceManager.GetString("Married", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no display name for the individual.
        /// </summary>
        public static string NoDisplayNameForIndividual {
            get {
                return ResourceManager.GetString("NoDisplayNameForIndividual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resident .
        /// </summary>
        public static string Resident {
            get {
                return ResourceManager.GetString("Resident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  was born on .
        /// </summary>
        public static string WasBornOn {
            get {
                return ResourceManager.GetString("WasBornOn", resourceCulture);
            }
        }
    }
}
