//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaiorumSeries.LaTeXExport {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MaiorumSeries.LaTeXExport.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancestors.
        /// </summary>
        internal static string Ancestors {
            get {
                return ResourceManager.GetString("Ancestors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child.
        /// </summary>
        internal static string Child {
            get {
                return ResourceManager.GetString("Child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brian W. Kernighan.
        /// </summary>
        internal static string CiteAuthor {
            get {
                return ResourceManager.GetString("CiteAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do what you think is interesting do something that you think is fun and worthwhile, because otherwise you won’t do it well anyway..
        /// </summary>
        internal static string CiteText {
            get {
                return ResourceManager.GetString("CiteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tribe Descendants from.
        /// </summary>
        internal static string ClanDescendantsFrom {
            get {
                return ResourceManager.GetString("ClanDescendantsFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tribe from .
        /// </summary>
        internal static string ClanFrom {
            get {
                return ResourceManager.GetString("ClanFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tribes.
        /// </summary>
        internal static string Clans {
            get {
                return ResourceManager.GetString("Clans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descendants.
        /// </summary>
        internal static string Descendants {
            get {
                return ResourceManager.GetString("Descendants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descendants from.
        /// </summary>
        internal static string DescendantsFrom {
            get {
                return ResourceManager.GetString("DescendantsFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        internal static string Family {
            get {
                return ResourceManager.GetString("Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father.
        /// </summary>
        internal static string Father {
            get {
                return ResourceManager.GetString("Father", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Index.
        /// </summary>
        internal static string GeneralIndex {
            get {
                return ResourceManager.GetString("GeneralIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated.
        /// </summary>
        internal static string Generated {
            get {
                return ResourceManager.GetString("Generated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generation.
        /// </summary>
        internal static string Generation {
            get {
                return ResourceManager.GetString("Generation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Husband.
        /// </summary>
        internal static string Husband {
            get {
                return ResourceManager.GetString("Husband", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index of names.
        /// </summary>
        internal static string IndexOfNames {
            get {
                return ResourceManager.GetString("IndexOfNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index of places.
        /// </summary>
        internal static string IndexOfPlaces {
            get {
                return ResourceManager.GetString("IndexOfPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Person.
        /// </summary>
        internal static string MainPerson {
            get {
                return ResourceManager.GetString("MainPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Person and Family.
        /// </summary>
        internal static string MainPersonAndFamily {
            get {
                return ResourceManager.GetString("MainPersonAndFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string Media {
            get {
                return ResourceManager.GetString("Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media File.
        /// </summary>
        internal static string MediaFile {
            get {
                return ResourceManager.GetString("MediaFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images for .
        /// </summary>
        internal static string MediaFor {
            get {
                return ResourceManager.GetString("MediaFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother.
        /// </summary>
        internal static string Mother {
            get {
                return ResourceManager.GetString("Mother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        internal static string PersonalEvents {
            get {
                return ResourceManager.GetString("PersonalEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Ste [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PrefaceText {
            get {
                return ResourceManager.GetString("PrefaceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preface.
        /// </summary>
        internal static string PrefaceTitle {
            get {
                return ResourceManager.GetString("PrefaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sources.
        /// </summary>
        internal static string Sources {
            get {
                return ResourceManager.GetString("Sources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wife.
        /// </summary>
        internal static string Wife {
            get {
                return ResourceManager.GetString("Wife", resourceCulture);
            }
        }
    }
}
